BOT_TOKEN = 'YOUR_BOT_TOKEN'
WEBHOOK_URI = 'https://your.webhook.uri/webhook'

MONGODB_DB = 'camp2017'
MONGODB_HOST = '127.0.0.1'
MONGODB_PORT = 27017

CURRENCY_NAME = '小石幣'
SCANNER_BUTTON_TEXT = '掃下去'
KEYWORD_MATCH_REWARD = 10
